ci: verify that the `action.yml` files are in sync
In https://github.com/mxschmitt/action-tmate/pull/218, I added a
convenient way to launch this Action in detached mode:
`mxschmitt/action-tmate/detached@v3`.

The way this is implemented is a copy/edited version of `action.yml` in
the `detached/` subdirectory.

This runs the danger of inadvertent divergences, as happened in
https://github.com/mxschmitt/action-tmate/pull/221 (which I caught in
time and the contributor gracefully addressed).

Let's add automation not only to update the file easily but also to
cause a failure in the PR build with a helpful message suggesting how to
fix the problem.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -13,6 +13,14 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: 20
+      - name: Verify that action.yml files are in sync
+        run: |
+          npm run update-detached-action.yml &&
+          if ! git diff --exit-code \*action.yml
+          then
+            echo '::error::action.yml files are not in sync, maybe run `npm run update-detached-action.yml`?'
+            exit 1
+          fi
       - name: Install dependencies
         run: npm ci
       - name: Run tests
